(() => {
  const defaults = { brandName:'Kopi Lane', tagline:"Single-origin espresso, bread baked in-house, and a room that doesn't mind if you stay.", hours:'7am–4pm daily. Last coffee at 3.45pm.', address:'22 Mill Road, city centre', accent:'#b85c38', menu:[{name:'Espresso & filter',description:'A rotating single origin, pulled properly.'},{name:'Bread & pastry',description:'Baked in the back before the doors open.'},{name:'All-day food',description:'Toasties, soup, and the sausage rolls people queue for.'}] };
  let config = structuredClone(defaults); let ready = false; let requestId = 0;
  const $ = id => document.getElementById(id); const announce = msg => $('notice').textContent = msg;
  const renderForm = () => { ['brandName','tagline','hours','address','accent'].forEach(key => $(key).value = config[key]); $('menu-fields').replaceChildren(...config.menu.map((item, i) => { const row=document.createElement('div'); row.className='menu-row field'; row.innerHTML=`<input class="input" aria-label="Menu item ${i+1} name" maxlength="60"><input class="input" aria-label="Menu item ${i+1} description" maxlength="140">`; row.children[0].value=item.name; row.children[1].value=item.description; return row; })); };
  const readForm = () => { config={brandName:$('brandName').value,tagline:$('tagline').value,hours:$('hours').value,address:$('address').value,accent:$('accent').value,menu:[...document.querySelectorAll('.menu-row')].map(row=>({name:row.children[0].value,description:row.children[1].value}))}; return config; };
  const send = () => { if(!ready) return; $('preview').contentWindow.postMessage({channel:'nightshift-preview',type:'NIGHTSHIFT_PREVIEW_UPDATE',requestId:++requestId,config:readForm()}, location.origin); };
  window.addEventListener('message', e => { if(e.origin!==location.origin || e.data?.channel!=='nightshift-preview') return; if(e.data.type==='NIGHTSHIFT_PREVIEW_READY'){ready=true;$('preview-status').textContent='Preview connected · changes are local only';send();} if(e.data.type==='NIGHTSHIFT_PREVIEW_ACK'){ $('errors').textContent=e.data.ok?'':e.data.errors.join(' ');$('preview-status').textContent=e.data.ok?'Preview updated · not published':'Preview needs a correction';} });
  $('editor-form').addEventListener('input', send); $('save').addEventListener('click',()=>{ readForm(); localStorage.setItem('nightshift:cafe:draft',JSON.stringify(config)); announce('Draft saved locally. Backend configuration pending; no Supabase write was attempted.'); }); $('publish').addEventListener('click',()=>announce('Publish is unavailable until backend configuration is applied. Nothing was sent.'));
  try { const saved=JSON.parse(localStorage.getItem('nightshift:cafe:draft')); if(saved) config=saved; } catch (_) {} renderForm();
})();
